config/routes.rb
Rails.application.routes.draw do
  get    "tasks", to: "tasks#index"
  get    "tasks/new", to: "tasks#new", as: :new_task
  post   "tasks", to: "tasks#create", as: :create
  get    "tasks/:id", to: "tasks#show", as: :task
  get    "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch  "tasks/:id",      to: "tasks#update"
  delete "tasks/:id",      to: "tasks#destroy", as: :destroy_task
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show() end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit() end

  def update
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task) %></h2>
  <p><%= task.completed %></p>
  <% if task.completed %>
   <input type="checkbox" name="completed" checked>
  <% else %>
   <input type="checkbox" name="completed">
  <% end %>
<% end %>

<h2><%= link_to "Add new task", new_task_path %></h2>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>A task</h1>

<h2><%= @task.title %></h2>
  <p><%= @task.completed %></p>
  <% if @task.completed %>
   <input type="checkbox" name="completed" checked>
  <% else %>
   <input type="checkbox" name="completed">
  <% end %>
  <p><%= @task.details %></p>

  <h2><%= link_to "Back", tasks_path %></h2>
  <h2><%= link_to "Edit", edit_task_path %></h2>
  <h2><%= link_to "Delete", destroy_task_path, method: :delete, data: { confirm: "Are you sure?" } %></h2>